---

  - name: Download RPM Package with checksum
    get_url: 
      url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.7.0-x86_64.rpm
      dest: /root/elasticsearch-7.7.0-x86_64.rpm
      checksum: sha512:https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.7.0-x86_64.rpm.sha512

  - name: Install ElasticSearch Package
    yum: 
      name: /root/elasticsearch-7.7.0-x86_64.rpm
      state: present
    notify: 
      - Elastic Start

  - meta: flush_handlers
    
  - name: Status Check
    uri: 
      url: http://localhost:9200
    register: elasticstatus

  - debug: var=elasticstatus.json.tagline
